version: '3'
services:
  jenkins:
    image: jenkins:01
    volumes:
      - /data/docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 2222:2222
      - 50000:50000