apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
  namespace: moni
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: grafana-data
          mountPath: /etc/grafana/provisioning
          subPath: provisioning/
        - name: grafana-data
          mountPath: /var/lib/grafana
          subPath: dashboards/
        - name: grafana-data
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
  volumes:
    - name: grafana-data
      persistentVolumeClaim:
        claimName: grafana-data
