apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: moni
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001